name: ubuntu-setup

on:
  push:

defaults:
  run:
    shell: bash
jobs:
  test-linux:
    strategy:
      matrix:
        options: ["", "--wsl", "--hpc", "--wsl --hpc", "--help"]
    timeout-minutes: 60 # Max execution time (min)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup
        run: ./setup ${{ matrix.options }}
