name: ubuntu-setup

on:
  push:
    paths:
      - "setup"
      - ".github/workflows/ci.yml"

defaults:
  run:
    shell: bash
jobs:
  test-linux:
    strategy:
      matrix:
        options: ["", "--wsl", "--hpc", "--wsl --hpc", "--help"]
    timeout-minutes: 60 # Max execution time (min)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install VSCode
        # In a WSL environment, VSCode is installed on the Windows side, but this repository only considers the Linux part.
        # Therefore, to test the --wsl option, VSCode must be installed manually before running the setup script.
        if: contains(matrix.options, '--wsl')
        run: |
          sudo apt-get install wget gpg apt-transport-https -y
          wget -qO- https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor >packages.microsoft.gpg
          sudo install -D -o root -g root -m 644 packages.microsoft.gpg /etc/apt/keyrings/packages.microsoft.gpg
          echo "deb [arch=amd64,arm64,armhf signed-by=/etc/apt/keyrings/packages.microsoft.gpg] https://packages.microsoft.com/repos/code stable main" | sudo tee /etc/apt/sources.list.d/vscode.list >/dev/null
          rm -f packages.microsoft.gpg
          sudo apt-get update && sudo apt-get install code -y
      - name: Setup
        run: GIT_USERNAME="test user" GIT_EMAIL="example@example.com" ./setup ${{ matrix.options }}
